"""Revision ID: 0a3e2ecfa319
Revises: 78adc69094db
Create Date: 2025-10-30 22:55:15.633382
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3e2ecfa319'
down_revision = '78adc69094db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.String(length=8), nullable=True),
    sa.Column('entry', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('sl', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('tp', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    op.create_unique_constraint('uq_accounts_user_broker_account', 'accounts', ['user_id', 'account_id'])
    op.create_index('ix_equitysnapshots_account_taken', 'equity_snapshots', ['account_id', 'taken_at'], unique=False)
    op.create_unique_constraint('uq_equitysnapshots_account_taken', 'equity_snapshots', ['account_id', 'taken_at'])
    op.add_column('trades', sa.Column('external_id', sa.String(length=64), nullable=True))
    op.create_index('ix_trades_account_closed', 'trades', ['account_id', 'closed_at'], unique=False)
    op.create_unique_constraint('uq_trades_account_external', 'trades', ['account_id', 'external_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_trades_account_external', 'trades', type_='unique')
    op.drop_index('ix_trades_account_closed', table_name='trades')
    op.drop_column('trades', 'external_id')
    op.drop_constraint('uq_equitysnapshots_account_taken', 'equity_snapshots', type_='unique')
    op.drop_index('ix_equitysnapshots_account_taken', table_name='equity_snapshots')
    op.drop_constraint('uq_accounts_user_broker_account', 'accounts', type_='unique')
    op.drop_table('signals')
    # ### end Alembic commands ###
